### ISSUE TITLE
Heirlooms deselect sold Heirlooms

### ISSUE THREAD

**Issue by puggan** [omsi6/omsi6.github.io#50]
**Describe the bug**
No way to select the equiped staff/shield, if you have sold all extra.

**To Reproduce**
1. Use an export with an extra staff
2. Select the extra staff
3. Use an export without an extra staff
4. No way to select the equiped staff

**Expected behavior**
Automaticly select the equiped staff if it's the only staff avaible.

**Screenshots**
![Screenshot from 2020-03-08 15-52-17](https://user-images.githubusercontent.com/866668/76165134-d95b2e00-6154-11ea-80f1-7a2c65db44ca.png)

**Comment by omsi6** [comment]
It already does automatically select your equipped staff if it can't find a match to the old staff you had previously selected. I'm not seeing the issue here.

**Comment by puggan** [comment]
So it's showing me the Equipped staff, but it's not marked as Equipped?

**Comment by omsi6** [comment]
Yes. There is no indicator for if an item that's being weighed is equipped, because by default, the calculator weighs your equipped items. The indicator is instead used when it's weighing an item that is *not* equipped, and is done so by highlighting the item you've selected that isn't equipped with a yellow outline.

**Comment by puggan** [comment]
In the Screenshoot there is clearly an indicator on my shield, saying it's the equiped one.

**Comment by omsi6** [comment]
Ah okay, the confusion here was due to me trying to explain to you that there was no actual bug, while myself failing to notice that there was indeed a bug, but it was purely a visual one (lack of the equipped marker in your first image).

I've pushed a fix for this now in v1.34 (b004afba787749aa5707867096599d260b7f9e9f), apologies for the misunderstanding and the delay.
